import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'firebase_options.dart';
import 'services/auth_service.dart';
import 'services/real_ble_service.dart';
import 'pages/home.dart';
import 'pages/login_page.dart';
import 'repositories/workout_repository.dart';

void main() async {
  // Ensure Flutter is ready before we do async work
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase — this connects your app to the Firebase project
  // using the config from firebase_options.dart (generated by flutterfire configure)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Create our auth service — this wraps Firebase Auth
    final authService = AuthService();

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      // StreamBuilder listens to Firebase auth state changes.
      // When user logs in → Firebase emits a User object → we show HomePage.
      // When user logs out → Firebase emits null → we show LoginPage.
      // This is REACTIVE — no manual navigation needed after login/logout!
      home: StreamBuilder<firebase_auth.User?>(
        stream: authService.authStateChanges,
        builder: (context, snapshot) {
          // Still loading auth state (e.g., checking if user was previously logged in)
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }

          // User is logged in → show home page
          if (snapshot.hasData) {
            return HomePage(
              bleService: RealBleService(),
              authService: authService,
              workoutRepository: HiveWorkoutRepository(),
            );
          }

          // No user → show login page
          return LoginPage(authService: authService);
        },
      ),
    );
  }
}
